<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="BDD Test Suite" duration-ms="134982" started-at="2023-07-27T08:44:12Z" finished-at="2023-07-27T08:46:27Z">
    <groups>
      <group name="cucumber">
        <method signature="TestRunner.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:testrunner.TestRunner@3cbcd8f3]" name="feature" class="testrunner.TestRunner"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Regression Test" duration-ms="134982" started-at="2023-07-27T08:44:12Z" finished-at="2023-07-27T08:46:27Z">
      <class name="testrunner.TestRunner">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:testrunner.TestRunner@3cbcd8f3]" name="setUpClass" is-config="true" duration-ms="1387" started-at="2023-07-27T14:14:12Z" finished-at="2023-07-27T14:14:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:testrunner.TestRunner@3cbcd8f3]" name="feature" duration-ms="40304" started-at="2023-07-27T14:14:14Z" description="Runs cucmber Features" data-provider="features" finished-at="2023-07-27T14:14:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CRC_BO_QA]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.NullPointerException
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at testrunner.TestRunner.feature(TestRunner.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.NullPointerException
	at stepdefinitions.SAStepDefination.APLogin(SAStepDefination.java:28)
	at âœ½.Given Login to AP(CRC_BO_QA.feature:47)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:testrunner.TestRunner@3cbcd8f3]" name="feature" duration-ms="92876" started-at="2023-07-27T14:14:54Z" description="Runs cucmber Features" data-provider="features" finished-at="2023-07-27T14:16:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CRC_FO_QA]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="testDownClass()[pri:0, instance:testrunner.TestRunner@3cbcd8f3]" name="testDownClass" is-config="true" duration-ms="9" started-at="2023-07-27T14:16:27Z" finished-at="2023-07-27T14:16:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDownClass -->
      </class> <!-- testrunner.TestRunner -->
    </test> <!-- Regression Test -->
  </suite> <!-- BDD Test Suite -->
</testng-results>
